name: Upload Sample Data to Supabase

on:
  schedule:
    - cron: '0 21 * * *'  # Runs every day at 9 PM UTC
  workflow_dispatch:

jobs:
  upload-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          npm install --force

      - name: Upload Sample Data to Supabase
        env:
          SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.NEXT_SERVICE_ROLE_KEY }}
        run: node scripts/uploadSampleData.js
